import {parseMidi,Performance} from './core.js';
import {Cube} from './cube.js';
const $=id=>document.getElementById(id),cube=new Cube($('cube'));
let lessons=[],lesson=null,midi=null,selected=null,audio=null,run=null,scoreURL=null;
let sessions=[];try{sessions=JSON.parse(localStorage.getItem('tutor.sessions.v1')||'[]');if(!Array.isArray(sessions))sessions=[];}catch{}
const say=text=>$('status').textContent=text;
const dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('tutor.lessons',1);r.onupgradeneeded=()=>r.result.createObjectStore('lessons',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
// Avoid an unhandled rejection if browser storage is unavailable at startup.
dbPromise.catch(()=>{});
async function records(method,value){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('lessons',method==='getAll'?'readonly':'readwrite');const req=tx.objectStore('lessons')[method](...(value===undefined?[]:[value]));tx.oncomplete=()=>resolve(req.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function showLessons(){const current=$('lesson').value;$('lesson').replaceChildren(...lessons.map(l=>new Option(l.title,l.id)));if(lessons.some(l=>l.id===current))$('lesson').value=current;}
function selectLesson(){if(run)finish(true);lesson=lessons.find(l=>l.id===$('lesson').value);if(!lesson)return;cube.reset();if(scoreURL)URL.revokeObjectURL(scoreURL);scoreURL=lesson.image instanceof Blob?URL.createObjectURL(lesson.image):null;const src=scoreURL||lesson.image;$('score').hidden=!src;$('scoreEmpty').hidden=!!src;if(src)$('score').src=src;else $('score').removeAttribute('src');$('score').alt=`Score: ${lesson.title}`;$('result').hidden=true;['dyn','tim','dur'].forEach(id=>$(id).textContent='—');say(`${lesson.notes.length} notes · ${Math.round(lesson.bpm)} BPM · ${lesson.warning||'Ready when you are.'}`);$('progress').value=0;$('progressText').textContent='';}
$('score').onerror=()=>{$('score').hidden=true;$('scoreEmpty').hidden=false;$('scoreEmpty').textContent='The score image could not be loaded. You can still practise this lesson.';};
function history(){ $('historyCount').textContent=sessions.length?`(${sessions.length})`:'';$('history').replaceChildren();for(const s of sessions.slice(0,30)){const row=document.createElement('div');row.className='history-row';const title=document.createElement('span');title.textContent=`${s.title} · ${new Date(s.date).toLocaleString()} · ${s.rate*100}% tempo${s.interrupted?' · stopped early':''}`;const scores=document.createElement('span');scores.textContent=`Dynamics ${Math.round(s.result.dynamics)}% · Timing ${Math.round(s.result.timing)}% · Duration ${Math.round(s.result.duration)}%`;row.append(title,scores);$('history').append(row);}if(!sessions.length)$('history').textContent='Your completed practices will appear here.';}
function renderResult(result,title){$('result').replaceChildren();const h=document.createElement('h2');h.textContent=title;$('result').append(h);const scores=document.createElement('div');scores.className='scores';for(const [key,label] of [['dynamics','Dynamics'],['timing','Timing'],['duration','Duration']]){const d=document.createElement('div'),v=document.createElement('strong'),l=document.createElement('span');v.textContent=`${Math.round(result[key])}%`;l.textContent=label;d.append(v,l);scores.append(d);}$('result').append(scores);const p=document.createElement('p');p.textContent=`${result.matched} / ${result.total} notes matched · ${result.missing} missed · ${result.extra} extra${result.unreleased?` · ${result.unreleased} unreleased`:''}`;$('result').append(p);$('result').hidden=false;}
async function soundReady(){if(!audio)audio=new AudioContext();await audio.resume();}
function tone(pitch,velocity,start,duration,click=false){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=click?'sine':'triangle';o.frequency.value=click?pitch:440*2**((pitch-69)/12);const t=Math.max(audio.currentTime,start),length=Math.max(.025,duration);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(click?.07:.10*velocity/127,t+.006);g.gain.exponentialRampToValueAtTime(.001,t+length);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+length+.03);if(run)run.voices.push(o);}
function lock(on){for(const id of ['lesson','tempo','importOpen','listen','demo','start','input','connect','click'])$(id).disabled=on;$('stop').disabled=!on;}
async function start(mode){if(!lesson||run)return;if(mode==='practice'&&!selected){say('Connect your piano and choose its MIDI input first.');return;}
 try{await soundReady();}catch{say('Audio could not start. Enable browser audio and try again.');return;}
 if(run)return;
 const rate=Number($('tempo').value),beat=60/lesson.bpm/rate,startAt=performance.now()/1000+beat*4+.15;
 run={mode,rate,beat,startAt,engine:new Performance(lesson.notes,rate),duration:lesson.duration/rate,voices:[],timers:[],nextBeat:0,nextNote:0,demoEvents:[],nextDemo:0,points:[],lastPoint:[0,0,0],lastCount:null};
 if(mode==='demo'){for(const [i,n] of run.engine.notes.entries()){const offset=Math.sin(i*.8)*.10,onset=n.onset+offset;run.demoEvents.push({on:true,pitch:n.pitch,velocity:Math.round(Math.max(1,Math.min(127,n.velocity+Math.cos(i)*12))),time:onset});run.demoEvents.push({on:false,pitch:n.pitch,time:onset+n.duration*(1+Math.sin(i*.9)*.25)});}run.demoEvents.sort((a,b)=>a.time-b.time);}
 cube.reset();$('result').hidden=true;lock(true);say('Get ready…');run.interval=setInterval(tick,20);tick();
}
function tick(){if(!run)return;const r=run,now=performance.now()/1000,t=now-r.startAt;
 const count=Math.ceil(-t/r.beat);if(t<0){if(count!==r.lastCount){r.lastCount=count;say(`${r.mode==='demo'?'Demo · ':r.mode==='listen'?'Listen · ':''}Count in: ${Math.min(4,count)}`);}}else say(r.mode==='practice'?'Playing · follow the score':r.mode==='demo'?'Demo · simulated performance':'Listening to the reference');
 // Schedule audio 120 ms ahead against the audio clock, not animation frames.
 while(r.nextBeat*r.beat-4*r.beat<t+.12){const at=r.nextBeat*r.beat-4*r.beat;if(at>r.duration)break;if(at<0||($('click').checked&&r.mode!=='listen'))tone(r.nextBeat%4===0?1000:750,90,audio.currentTime+at-t,.045,true);r.nextBeat++;}
 if(r.mode==='listen'){while(r.nextNote<r.engine.notes.length&&r.engine.notes[r.nextNote].onset<t+.12){const n=r.engine.notes[r.nextNote++];tone(n.pitch,n.velocity,audio.currentTime+n.onset-t,n.duration);}}
 if(r.mode==='demo'){while(r.nextDemo<r.demoEvents.length&&r.demoEvents[r.nextDemo].time<=t){const e=r.demoEvents[r.nextDemo++];receive(e.on,e.pitch,e.velocity,e.time,0);if(e.on)tone(e.pitch,e.velocity,audio.currentTime,.25);}}
 $('progress').value=Math.max(0,Math.min(1,t/r.duration));$('progressText').textContent=t<0?'':`${Math.min(r.duration,Math.max(0,t)).toFixed(1)} / ${r.duration.toFixed(1)} s`;
 if(t>r.duration+1.5)finish(false);
}
function receive(on,pitch,velocity,time,channel){if(!run||run.mode==='listen')return;const r=run;if(time<-.5)return;const m=on?r.engine.on(pitch,velocity,time,channel):r.engine.off(pitch,time,channel);if(!m)return;const point=r.engine.point(m,r.lastPoint);r.lastPoint=point;cube.set(point);r.points.push({t:time,p:point});$('dyn').textContent=`${m.dynamics>0?'+':''}${m.dynamics} velocity`;$('tim').textContent=`${Math.round(Math.abs(m.timing)*1000)} ms ${m.timing<0?'early':'late'}`;if(m.duration!==null)$('dur').textContent=`${Math.round(Math.abs(m.duration)*100)}% ${m.duration<0?'shorter':'longer'}`;}
function finish(interrupted){if(!run)return;const r=run;run=null;clearInterval(r.interval);for(const v of r.voices){try{v.stop();}catch{}}cube.live=false;lock(false);
 if(r.mode!=='listen'){const result=r.engine.result();renderResult(result,r.mode==='demo'?'Demo results':interrupted?'Practice stopped':'Practice complete');if(r.mode==='practice'){const record={title:lesson.title,lesson:lesson.id,date:new Date().toISOString(),rate:r.rate,interrupted,result,matches:r.engine.matches,trace:r.points};sessions.unshift(record);sessions=sessions.slice(0,50);try{localStorage.setItem('tutor.sessions.v1',JSON.stringify(sessions));say(interrupted?'Stopped. Partial session saved.':'Session saved. Take a breath, then try again.');}catch{say('Session finished, but browser storage is full or unavailable. This result has not been saved.');}history();}else say('Demo finished. Connect a piano to practise yourself.');}else say('Reference finished. Ready to practise.');
}
function bindInput(){if(selected)selected.onmidimessage=null;selected=midi?.inputs.get($('input').value)||null;if(selected){selected.onmidimessage=e=>{const [status,pitch,velocity]=e.data,kind=status>>4;if(!run){if(kind===9&&velocity>0)say(`Piano received · note ${pitch}, velocity ${velocity}`);return;}if(run.mode!=='practice')return;const time=e.timeStamp/1000-run.startAt;if(kind===9||kind===8)receive(kind===9&&velocity>0,pitch,velocity,time,status&15);};try{localStorage.setItem('tutor.input',selected.id);}catch{}say(`${selected.name||'Piano'} connected.`);}}
function inputs(){const old=selected?.id||$('input').value;let saved='';try{saved=localStorage.getItem('tutor.input')||'';}catch{}const list=[...midi.inputs.values()].filter(p=>p.state==='connected');$('input').replaceChildren(new Option('Choose MIDI input',''),...list.map(p=>new Option(p.name||'MIDI input',p.id)));const chosen=list.find(p=>p.id===old)||list.find(p=>p.id===saved)||(list.length===1?list[0]:null);if(selected&&!list.some(p=>p.id===selected.id)){if(run)finish(true);say('Piano disconnected. Reconnect it before starting again.');}if(chosen)$('input').value=chosen.id;bindInput();if(!list.length)say('No MIDI inputs found. Connect the piano, then check its USB/MIDI settings.');}
$('connect').onclick=async()=>{if(!navigator.requestMIDIAccess){say('This browser does not support Web MIDI. Try desktop Chrome or Edge.');return;}try{midi=await navigator.requestMIDIAccess({sysex:false});midi.onstatechange=inputs;inputs();}catch{say('MIDI access was not granted. Check the browser’s site permissions, then reconnect.');}};
$('input').onchange=bindInput;$('lesson').onchange=selectLesson;$('start').onclick=()=>start('practice');$('listen').onclick=()=>start('listen');$('demo').onclick=()=>start('demo');$('stop').onclick=()=>finish(true);
$('focus').onclick=()=>{const on=document.body.classList.toggle('focus');$('focus').textContent=on?'Exit focus':'Focus view';};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&run)finish(true);});
$('importOpen').onclick=()=>{$('importError').textContent='';$('importDialog').showModal();};$('cancel').onclick=()=>$('importDialog').close();
$('importForm').onsubmit=async e=>{e.preventDefault();try{const mf=$('midiFile').files[0],im=$('imageFile').files[0];if(mf.size>5e6||im.size>15e6)throw Error('Use a MIDI under 5 MB and an image under 15 MB.');const buffer=await mf.arrayBuffer(),parsed=parseMidi(buffer);if(parsed.notes.length>20000)throw Error('Use a shorter lesson (up to 20,000 notes).');const l={id:crypto.randomUUID(),title:$('title').value.trim()||mf.name,...parsed,image:im};await records('put',l);lessons.push(l);showLessons();$('lesson').value=l.id;selectLesson();$('importDialog').close();$('importForm').reset();}catch(error){$('importError').textContent=`Could not add lesson: ${error.message}`;}};
async function init(){history();try{const response=await fetch('./lessons/index.json');if(!response.ok)throw Error('Lesson list unavailable.');const entries=await response.json();for(const entry of entries){const response=await fetch(entry.midi);if(!response.ok)throw Error(`Could not load ${entry.title}.`);const parsed=parseMidi(await response.arrayBuffer());lessons.push({...entry,...parsed});}}catch(error){say(error.message);}try{lessons.push(...await records('getAll'));}catch{say('Local lesson storage is unavailable. Built-in lessons still work.');}showLessons();if(lessons.length)selectLesson();else say('Add a MIDI file and score image to begin.');}
init();
