import {parseMidi,Performance} from './core.js';
import {Cube} from './cube.js';
import {PracticeReport} from './report.js';
import {makeReport} from './report-data.js';
import {loadLibraryLesson,validLessonId} from './library.js';
const $=id=>document.getElementById(id),cube=new Cube($('cube')),review=new PracticeReport();
let lessons=[],lesson=null,midi=null,selected=null,audio=null,run=null,scoreURL=null,zoom=1,fitPage=true;
let sessions=[];try{sessions=JSON.parse(localStorage.getItem('tutor.sessions.v1')||'[]');if(!Array.isArray(sessions))sessions=[];}catch{}
const say=text=>$('status').textContent=text;
const dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('tutor.lessons',1);r.onupgradeneeded=()=>r.result.createObjectStore('lessons',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
// Avoid an unhandled rejection if browser storage is unavailable at startup.
dbPromise.catch(()=>{});
async function records(method,value){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('lessons',method==='getAll'?'readonly':'readwrite');const req=tx.objectStore('lessons')[method](...(value===undefined?[]:[value]));tx.oncomplete=()=>resolve(req.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function showLessons(){const current=$('lesson').value;$('lesson').replaceChildren(...lessons.map(l=>new Option(l.title,l.id)));if(lessons.some(l=>l.id===current))$('lesson').value=current;}
function selectLesson(updateURL=true){if(run)finish(true);review.reset();lesson=lessons.find(l=>l.id===$('lesson').value);if(!lesson)return;cube.reset();if(scoreURL)URL.revokeObjectURL(scoreURL);scoreURL=lesson.image instanceof Blob?URL.createObjectURL(lesson.image):null;const src=scoreURL||lesson.image;$('scoreEmpty').textContent='No score image for this lesson yet. You can listen to the reference and practise with the MIDI.';zoom=1;fitPage=true;layoutScore();$('scoreViewport').scrollTo(0,0);$('share').disabled=!lesson.shared;if(updateURL){const url=new URL(location.href);if(lesson.shared)url.searchParams.set('lesson',lesson.id);else url.searchParams.delete('lesson');window.history.replaceState(null,'',url);}$('score').hidden=!src;$('scoreEmpty').hidden=!!src;if(src)$('score').src=src;else $('score').removeAttribute('src');$('score').alt=`Score: ${lesson.title}`;$('result').hidden=true;['dyn','tim','dur'].forEach(id=>$(id).textContent='—');say(`${lesson.notes.length} notes · ${Math.round(lesson.bpm)} BPM · ${lesson.warning||'Ready when you are.'}`);$('progress').value=0;$('progressText').textContent='';}
$('score').onerror=()=>{$('score').hidden=true;$('scoreEmpty').hidden=false;$('scoreEmpty').textContent='The score image could not be loaded. You can still practise this lesson.';};
function history(){ $('historyCount').textContent=sessions.length?`(${sessions.length})`:'';$('history').replaceChildren();for(const s of sessions.slice(0,30)){const row=document.createElement('div');row.className='history-row';const title=document.createElement('span');title.textContent=`${s.title} · ${new Date(s.date).toLocaleString()} · ${s.rate*100}% tempo${s.interrupted?' · stopped early':''}`;const scores=document.createElement('span');scores.textContent=`Dynamics ${Math.round(s.result.dynamics)}% · Timing ${Math.round(s.result.timing)}% · Duration ${Math.round(s.result.duration)}%`;row.append(title,scores);if(s.report){const button=document.createElement('button');button.textContent='Review';button.onclick=()=>{if(run)return;const target=lessons.find(l=>l.id===s.lesson)||null;if(target){$('lesson').value=target.id;selectLesson();}renderResult(s.result,s.interrupted?'Saved partial practice':'Saved practice');review.show(s.report,target);$('performanceReview').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});};row.append(button);}$('history').append(row);}if(!sessions.length)$('history').textContent='Your completed practices will appear here.';}
function renderResult(result,title){$('result').replaceChildren();const h=document.createElement('h2');h.textContent=title;$('result').append(h);const scores=document.createElement('div');scores.className='scores';for(const [key,label] of [['dynamics','Dynamics'],['timing','Timing'],['duration','Duration']]){const d=document.createElement('div'),v=document.createElement('strong'),l=document.createElement('span');v.textContent=`${Math.round(result[key])}%`;l.textContent=label;d.append(v,l);scores.append(d);}$('result').append(scores);const p=document.createElement('p');p.textContent=`${result.matched} / ${result.total} notes matched · ${result.missing} missed · ${result.extra} extra${result.unreleased?` · ${result.unreleased} unreleased`:''}`;$('result').append(p);const reviewLink=document.createElement('a');reviewLink.href='#performanceReview';reviewLink.textContent='Review the phrase';$('result').append(reviewLink);$('result').hidden=false;}
async function soundReady(){if(!audio)audio=new AudioContext();await audio.resume();}
function tone(pitch,velocity,start,duration,click=false){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=click?'sine':'triangle';o.frequency.value=click?pitch:440*2**((pitch-69)/12);const t=Math.max(audio.currentTime,start),length=Math.max(.025,duration);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(click?.07:.10*velocity/127,t+.006);g.gain.exponentialRampToValueAtTime(.001,t+length);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+length+.03);if(run)run.voices.push(o);}
function lock(on){for(const id of ['lesson','tempo','importOpen','listen','demo','start','input','connect','click'])$(id).disabled=on;$('stop').disabled=!on;}
async function start(mode){if(!lesson||run)return;if(mode==='practice'&&!selected){say('Connect your piano and choose its MIDI input first.');return;}
 try{await soundReady();}catch{say('Audio could not start. Enable browser audio and try again.');return;}
 if(run)return;
 const rate=Number($('tempo').value),beat=60/lesson.bpm/rate,startAt=performance.now()/1000+beat*4+.15;
 run={mode,rate,beat,startAt,engine:new Performance(lesson.notes,rate),duration:lesson.duration/rate,voices:[],timers:[],nextBeat:0,nextNote:0,demoEvents:[],nextDemo:0,points:[],lastPoint:[0,0,0],lastCount:null};
 if(mode==='demo'){for(const [i,n] of run.engine.notes.entries()){const offset=Math.sin(i*.8)*.10,onset=n.onset+offset;run.demoEvents.push({on:true,pitch:n.pitch,velocity:Math.round(Math.max(1,Math.min(127,n.velocity+Math.cos(i)*12))),time:onset});run.demoEvents.push({on:false,pitch:n.pitch,time:onset+n.duration*(1+Math.sin(i*.9)*.25)});}run.demoEvents.sort((a,b)=>a.time-b.time);}
 cube.reset();review.reset();$('result').hidden=true;lock(true);say('Get ready…');run.interval=setInterval(tick,20);tick();
}
function tick(){if(!run)return;const r=run,now=performance.now()/1000,t=now-r.startAt;
 const count=Math.ceil(-t/r.beat);if(t<0){if(count!==r.lastCount){r.lastCount=count;say(`${r.mode==='demo'?'Demo · ':r.mode==='listen'?'Listen · ':''}Count in: ${Math.min(4,count)}`);}}else say(r.mode==='practice'?'Playing · follow the score':r.mode==='demo'?'Demo · simulated performance':'Listening to the reference');
 // Schedule audio 120 ms ahead against the audio clock, not animation frames.
 while(r.nextBeat*r.beat-4*r.beat<t+.12){const at=r.nextBeat*r.beat-4*r.beat;if(at>r.duration)break;if(at<0||($('click').checked&&r.mode!=='listen'))tone(r.nextBeat%4===0?1000:750,90,audio.currentTime+at-t,.045,true);r.nextBeat++;}
 if(r.mode==='listen'){while(r.nextNote<r.engine.notes.length&&r.engine.notes[r.nextNote].onset<t+.12){const n=r.engine.notes[r.nextNote++];tone(n.pitch,n.velocity,audio.currentTime+n.onset-t,n.duration);}}
 if(r.mode==='demo'){while(r.nextDemo<r.demoEvents.length&&r.demoEvents[r.nextDemo].time<=t){const e=r.demoEvents[r.nextDemo++];receive(e.on,e.pitch,e.velocity,e.time,0);if(e.on)tone(e.pitch,e.velocity,audio.currentTime,.25);}}
 $('progress').value=Math.max(0,Math.min(1,t/r.duration));$('progressText').textContent=t<0?'':`${Math.min(r.duration,Math.max(0,t)).toFixed(1)} / ${r.duration.toFixed(1)} s`;
 if(t>r.duration+1.5)finish(false);
}
function receive(on,pitch,velocity,time,channel){if(!run||run.mode==='listen')return;const r=run;if(time<-.5)return;const m=on?r.engine.on(pitch,velocity,time,channel):r.engine.off(pitch,time,channel);if(!m)return;const point=r.engine.point(m,r.lastPoint);r.lastPoint=point;cube.set(point);r.points.push({t:time,p:point});$('dyn').textContent=`${m.dynamics>0?'+':''}${m.dynamics} velocity`;$('tim').textContent=`${Math.round(Math.abs(m.timing)*1000)} ms ${m.timing<0?'early':'late'}`;if(m.duration!==null)$('dur').textContent=`${Math.round(Math.abs(m.duration)*100)}% ${m.duration<0?'shorter':'longer'}`;}
function finish(interrupted){if(!run)return;const r=run;run=null;clearInterval(r.interval);for(const v of r.voices){try{v.stop();}catch{}}cube.live=false;lock(false);
 if(r.mode!=='listen'){const result=r.engine.result();const report=makeReport(r.engine,{title:lesson.title,rate:r.rate,duration:r.duration,endedAt:performance.now()/1000-r.startAt,interrupted,demo:r.mode==='demo',reference:lesson.notes});renderResult(result,r.mode==='demo'?'Demo results':interrupted?'Practice stopped':'Practice complete');review.show(report,lesson);if(r.mode==='practice'){const record={title:lesson.title,lesson:lesson.id,date:new Date().toISOString(),rate:r.rate,interrupted,result,matches:r.engine.matches,trace:r.points,report};sessions.unshift(record);sessions=sessions.slice(0,50);try{localStorage.setItem('tutor.sessions.v1',JSON.stringify(sessions));say(interrupted?'Stopped. Partial session saved.':'Session saved. Take a breath, then try again.');}catch{say('Session finished, but browser storage is full or unavailable. This result has not been saved.');}history();}else say('Demo finished. Connect a piano to practise yourself.');}else say('Reference finished. Ready to practise.');
}
function bindInput(){if(selected)selected.onmidimessage=null;selected=midi?.inputs.get($('input').value)||null;if(selected){selected.onmidimessage=e=>{const [status,pitch,velocity]=e.data,kind=status>>4;if(!run){if(kind===9&&velocity>0)say(`Piano received · note ${pitch}, velocity ${velocity}`);return;}if(run.mode!=='practice')return;const time=e.timeStamp/1000-run.startAt;if(kind===9||kind===8)receive(kind===9&&velocity>0,pitch,velocity,time,status&15);};try{localStorage.setItem('tutor.input',selected.id);}catch{}say(`${selected.name||'Piano'} connected.`);}}
function inputs(){const old=selected?.id||$('input').value;let saved='';try{saved=localStorage.getItem('tutor.input')||'';}catch{}const list=[...midi.inputs.values()].filter(p=>p.state==='connected');$('input').replaceChildren(new Option('Choose MIDI input',''),...list.map(p=>new Option(p.name||'MIDI input',p.id)));const chosen=list.find(p=>p.id===old)||list.find(p=>p.id===saved)||(list.length===1?list[0]:null);if(selected&&!list.some(p=>p.id===selected.id)){if(run)finish(true);say('Piano disconnected. Reconnect it before starting again.');}if(chosen)$('input').value=chosen.id;bindInput();if(!list.length)say('No MIDI inputs found. Connect the piano, then check its USB/MIDI settings.');}
$('connect').onclick=async()=>{if(!navigator.requestMIDIAccess){say('This browser does not support Web MIDI. Try desktop Chrome or Edge.');return;}try{midi=await navigator.requestMIDIAccess({sysex:false});midi.onstatechange=inputs;inputs();}catch{say('MIDI access was not granted. Check the browser’s site permissions, then reconnect.');}};
$('input').onchange=bindInput;$('lesson').onchange=()=>selectLesson();$('start').onclick=()=>start('practice');$('listen').onclick=()=>start('listen');$('demo').onclick=()=>start('demo');$('stop').onclick=()=>finish(true);
// Browser fullscreen requires user activation. Persist intent, not an assumed state.
let wantsFullscreen=false,pendingFullscreen=false,fullscreenBusy=false;
try{wantsFullscreen=localStorage.getItem('tutor.fullscreen')==='1';}catch{}
const fullscreenParam=new URLSearchParams(location.search).get('fullscreen');
if(fullscreenParam!==null)wantsFullscreen=['','1','true'].includes(fullscreenParam.toLowerCase());
pendingFullscreen=wantsFullscreen;
function fullscreenLabel(){const active=!!document.fullscreenElement;$('fullscreen').textContent=active?'Exit full screen':'Full screen';$('fullscreen').setAttribute('aria-pressed',String(active));$('fullscreen').title=pendingFullscreen?'Full screen will open on your next click.':'Expand the practice space';}
function rememberFullscreen(value){wantsFullscreen=value;try{localStorage.setItem('tutor.fullscreen',value?'1':'0');}catch{}const url=new URL(location.href);url.searchParams.set('fullscreen',value?'1':'0');window.history.replaceState(null,'',url);}
async function enterFullscreen(){if(fullscreenBusy||document.fullscreenElement)return;pendingFullscreen=false;fullscreenBusy=true;try{if(!document.documentElement.requestFullscreen)throw Error('unsupported');await document.documentElement.requestFullscreen();rememberFullscreen(true);}catch{say('Full screen could not open. Use the Full screen button or your browser’s full-screen command.');}finally{fullscreenBusy=false;fullscreenLabel();}}
$('fullscreen').onclick=async()=>{pendingFullscreen=false;if(document.fullscreenElement){try{await document.exitFullscreen();rememberFullscreen(false);}catch{say('Could not exit full screen. Press Escape to leave it.');}}else await enterFullscreen();fullscreenLabel();};
document.addEventListener('fullscreenchange',()=>{fullscreenLabel();requestAnimationFrame(layoutScore);});
// Do not consume activation needed by file pickers, MIDI permission or clipboard.
document.addEventListener('click',event=>{if(pendingFullscreen&&!event.target.closest('input,select,a,#fullscreen,#connect,#share,#importOpen'))void enterFullscreen();},true);
fullscreenLabel();
function layoutScore(){const view=$('scoreViewport'),available=Math.max(100,view.clientWidth-32),fit=Math.min(available,Math.max(100,view.clientHeight-32)*210/297),width=(fitPage?fit:available)*zoom;$('scorePage').style.width=`${width}px`;$('zoomValue').textContent=fitPage?'Fit':`${Math.round(zoom*100)}%`;$('zoomOut').disabled=!fitPage&&zoom<=.2;$('zoomIn').disabled=!fitPage&&zoom>=3;}
new ResizeObserver(layoutScore).observe($('scoreViewport'));
function changeZoom(delta){if(fitPage){const view=$('scoreViewport');zoom=$('scorePage').clientWidth/Math.max(100,view.clientWidth-32);fitPage=false;}zoom=Math.max(.2,Math.min(3,Math.round((zoom+delta)*100)/100));layoutScore();}
$('zoomOut').onclick=()=>changeZoom(-.15);$('zoomIn').onclick=()=>changeZoom(.15);$('zoomFit').onclick=()=>{fitPage=true;zoom=1;layoutScore();$('scoreViewport').scrollTo(0,0);};
$('share').onclick=async()=>{if(!lesson?.shared)return;const url=new URL(location.href);url.searchParams.set('lesson',lesson.id);if(wantsFullscreen)url.searchParams.set('fullscreen','1');try{await navigator.clipboard.writeText(url.href);say('Lesson link copied.');}catch{say(`Copy the lesson link from your browser’s address bar: ${url.href}`);}};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&run)finish(true);});
$('importOpen').onclick=()=>{$('importError').textContent='';$('importDialog').showModal();};$('cancel').onclick=()=>$('importDialog').close();
$('importForm').onsubmit=async e=>{e.preventDefault();try{const mf=$('midiFile').files[0],im=$('imageFile').files[0];if(mf.size>5e6||(im?.size||0)>15e6)throw Error('Use a MIDI under 5 MB and an image under 15 MB.');const buffer=await mf.arrayBuffer(),parsed=parseMidi(buffer);if(parsed.notes.length>20000)throw Error('Use a shorter lesson (up to 20,000 notes).');const l={id:crypto.randomUUID(),title:$('title').value.trim()||mf.name,...parsed,image:im||null};await records('put',l);lessons.push(l);showLessons();$('lesson').value=l.id;selectLesson();$('importDialog').close();$('importForm').reset();}catch(error){$('importError').textContent=`Could not add lesson: ${error.message}`;}};
async function init(){
 history();const warnings=[];const requested=new URLSearchParams(location.search).get('lesson');
 try{const response=await fetch('./library/index.json');if(!response.ok)throw Error('Lesson library unavailable.');const entries=await response.json();if(!Array.isArray(entries))throw Error('Invalid lesson library.');const loaded=await Promise.allSettled(entries.map(entry=>loadLibraryLesson(typeof entry==='string'?entry:entry.id)));for(const result of loaded){if(result.status==='fulfilled')lessons.push(result.value);else warnings.push(result.reason.message);}}catch(error){warnings.push(error.message);}
 if(requested&&!lessons.some(l=>l.id===requested)){try{if(!validLessonId(requested))throw Error('Invalid lesson link. Use a folder name containing letters, numbers, hyphens or underscores.');lessons.push(await loadLibraryLesson(requested));}catch(error){warnings.push(`Could not open lesson “${requested}”: ${error.message}`);}}
 try{const local=await records('getAll');lessons.push(...local.filter(l=>!lessons.some(existing=>existing.id===l.id)).map(l=>({...l,shared:false})));}catch{warnings.push('Local lesson storage is unavailable.');}
 showLessons();if(requested&&lessons.some(l=>l.id===requested))$('lesson').value=requested;
 if(lessons.length)selectLesson(!requested||lessons.some(l=>l.id===requested));else say('Add a MIDI file to begin.');
 if(warnings.length)say(warnings.join(' '));
}
init();
