import test from 'node:test';
import assert from 'node:assert/strict';
import {Performance} from '../core.js';
import {makeReport,groupReport,validPositions,imageBox,referenceKey,deviationText} from '../report-data.js';
const note=(pitch=60,onset=0,duration=1)=>({pitch,velocity:72,onset,duration});
function report(p,reference,extra={}){return makeReport(p,{title:'Test',rate:1,duration:5,endedAt:6,reference,...extra});}
test('timeline uses reference time and retains signed raw errors',()=>{const notes=[note(60,1)],p=new Performance(notes,.5);p.on(60,88,2.125);p.off(60,5.125);const r=report(p,notes,{rate:.5});assert.equal(r.points[0].time,2);assert.equal(r.points[0].playedAt,2.125);assert.deepEqual(r.points[0].values,{dynamics:50,timing:50,duration:50});assert.equal(deviationText(r.points[0],'timing'),'50% · 125 ms late');});
test('perfect notes and missed notes reproduce the headline numerators',()=>{const notes=[note(),note(62,2)],p=new Performance(notes);p.on(60,72,0);p.off(60,1);p.on(80,90,2.1);const r=report(p,notes);assert.deepEqual(r.points[0].values,{dynamics:100,timing:100,duration:100});assert.equal(r.points[1].state,'missed');assert.equal(r.points[1].values.dynamics,0);assert.equal(r.extras[0].onset,2.1);for(const key of ['dynamics','timing','duration'])assert.equal(r.points.reduce((s,n)=>s+n.values[key],0)/(notes.length+r.extras.length),p.result()[key]);});
test('chord averaging cannot cancel opposing errors',()=>{const notes=[note(60),note(64)],p=new Performance(notes);p.on(60,88,0);p.on(64,56,0);p.off(60,1);p.off(64,1);const groups=groupReport(report(p,notes).points);assert.equal(groups.length,1);assert.equal(groups[0].values.dynamics,50);assert.equal(groups[0].points.length,2);});
test('unfinished exercises distinguish missed notes from those not reached',()=>{const notes=[note(60,0),note(62,4)],p=new Performance(notes);const r=report(p,notes,{endedAt:1,interrupted:true});assert.equal(r.points[0].state,'missed');assert.equal(r.points[1].state,'not-reached');assert.equal(r.points[1].values.timing,null);});
test('unreleased keys receive duration zero without inventing a measured duration',()=>{const notes=[note()],p=new Performance(notes);p.on(60,72,0);const point=report(p,notes).points[0];assert.equal(point.values.duration,0);assert.equal(point.raw.duration,null);assert.equal(deviationText(point,'duration'),'Key not released');});
test('position maps exclude malformed coordinates and out-of-range notes',()=>{assert.deepEqual(validPositions([{index:0,x:.1,y:.2},{index:0,x:.2,y:.3},{index:1,x:2,y:.4},{index:7,x:0,y:0},null],2),[{index:0,x:.2,y:.3}]);});
test('overlays follow the actual contained image through zoom and letterboxing',()=>{const a=imageBox(500,700,400,800);assert.deepEqual(a,{x:75,y:0,width:350,height:700});const b=imageBox(1000,1400,400,800);assert.equal(b.x+a.x,b.x*1.5);assert.equal(b.width,a.width*2);assert.deepEqual(imageBox(500,700,1000,200),{x:0,y:0,width:500,height:100});});
test('saved reports detect changes in the reference before overlaying a score',()=>{const a=[note()],b=[note(62)];assert.notEqual(referenceKey(a),referenceKey(b));assert.equal(referenceKey(a),referenceKey(structuredClone(a)));});
